use rusqlite::{Connection, params};
use std::{fs, path::PathBuf};
use chrono::Utc;
use crate::models::{Host, HostUpsert};

pub fn open() -> rusqlite::Result<Connection> { let dir = std::env::var_os("LOCALAPPDATA").map(PathBuf::from).unwrap_or_else(|| PathBuf::from(".")); let dir = dir.join("TermPilot").join("data"); fs::create_dir_all(&dir).ok(); let c = Connection::open(dir.join("termpilot.db"))?; c.pragma_update(None, "journal_mode", "WAL")?; c.pragma_update(None, "foreign_keys", true)?; c.busy_timeout(std::time::Duration::from_secs(5))?; c.execute_batch(include_str!("../migrations/001_init.sql"))?; Ok(c) }
pub fn hosts(c: &Connection) -> rusqlite::Result<Vec<Host>> { let mut s = c.prepare("SELECT id,name,connection_type,address,port,username,auth_method,group_name,is_production,endpoint_fingerprint FROM hosts WHERE deleted_at IS NULL ORDER BY name")?; let rows = s.query_map([], |r| Ok(Host { id:r.get(0)?, name:r.get(1)?, connection_type:r.get(2)?, address:r.get(3)?, port:r.get(4)?, username:r.get(5)?, auth_method:r.get(6)?, group_name:r.get(7)?, is_production:r.get::<_,i64>(8)? != 0, endpoint_fingerprint:r.get(9)? }))?; rows.collect() }
pub fn upsert(c: &Connection, h: &HostUpsert) -> rusqlite::Result<String> { let id = h.id.clone().unwrap_or_else(|| uuid::Uuid::new_v4().to_string()); let now = Utc::now().to_rfc3339(); c.execute("INSERT INTO hosts(id,name,connection_type,address,port,username,auth_method,group_name,is_production,policy_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,connection_type=excluded.connection_type,address=excluded.address,port=excluded.port,username=excluded.username,auth_method=excluded.auth_method,group_name=excluded.group_name,is_production=excluded.is_production,policy_id=excluded.policy_id,updated_at=excluded.updated_at", params![id,h.name,h.connection_type,h.address,h.port,h.username,h.auth_method,h.group_name,h.is_production as i32,h.policy_id,now,now])?; Ok(id) }
pub fn delete(c: &Connection, id: &str) -> rusqlite::Result<bool> { Ok(c.execute("UPDATE hosts SET deleted_at=? WHERE id=? AND deleted_at IS NULL", params![Utc::now().to_rfc3339(),id])? == 1) }
