import * as React from 'react';
import { useEffect, useRef, useState } from 'react';
import type { ReactNode } from 'react';
import { api } from './lib/tauri';
import type { Host, Session } from './types';
import { Terminal as XTerminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import '@xterm/xterm/css/xterm.css';

type NavIconName = 'dashboard' | 'hosts' | 'terminal' | 'transfer' | 'audit' | 'settings';
const nav: Array<[string, NavIconName]> = [['总览', 'dashboard'], ['主机', 'hosts'], ['终端', 'terminal'], ['SFTP', 'transfer'], ['审计', 'audit'], ['设置', 'settings']];

function NavIcon({ name }: { name: NavIconName }) {
  const shapes: Record<NavIconName, ReactNode> = {
    dashboard: <><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,
    hosts: <><path d="M7 9.5a4 4 0 1 1 2.8 3.8L7.5 16H5v2H3v-3.2l4.7-4.7A4 4 0 0 1 7 9.5Z"/><path d="m15 16 3 3m-1.5-1.5 2-2"/></>,
    terminal: <><path d="m4 7 5 5-5 5"/><path d="M12 17h8"/></>,
    transfer: <><path d="M4 8h15"/><path d="m15 4 4 4-4 4"/><path d="M20 16H5"/><path d="m9 12-4 4 4 4"/></>,
    audit: <><path d="M5 20V11"/><path d="M12 20V5"/><path d="M19 20v-8"/><path d="M3 20h18"/></>,
    settings: <><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-1.8 1.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.5v.1h-2.6v-.1a1.7 1.7 0 0 0-1-1.5 1.7 1.7 0 0 0-1.9.3l-.1.1-1.8-1.8.1-.1a1.7 1.7 0 0 0 .3-1.9 1.7 1.7 0 0 0-1.5-1H6v-2.6h.1a1.7 1.7 0 0 0 1.5-1 1.7 1.7 0 0 0-.3-1.9l-.1-.1L9 6.6l.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.5v-.1h2.6v.1a1.7 1.7 0 0 0 1 1.5 1.7 1.7 0 0 0 1.9-.3l.1-.1 1.8 1.8-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.5 1h.1V14h-.1a1.7 1.7 0 0 0-1.5 1Z"/></>
  };
  return <svg className="nav-svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{shapes[name]}</svg>;
}

export default function App() {
  const [page, setPage] = useState('总览');
  const [hosts, setHosts] = useState<Host[]>([]);
  const [session, setSession] = useState<Session>();
  const [agentOpen, setAgentOpen] = useState(true);
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [theme, setTheme] = useState<'dark' | 'light'>('dark');
  useEffect(() => { api.hosts().then(setHosts); }, []);
  const connect = async (host: Host) => { setSession(await api.connect(host.id)); setPage('终端'); };
  const pageTitle = page === '终端' ? '远程终端' : page === '主机' ? '主机管理' : page === 'SFTP' ? 'SFTP 文件管理' : page === '审计' ? '本地审计' : page;

  return <div className={'app ' + (theme === 'light' ? 'theme-light' : '')}>
    <aside className={'side ' + (sidebarCollapsed ? 'collapsed' : '')}>
      <div className="brand"><span className="logo"><span>TP</span></span><b>TermPilot</b></div>
      <nav>{nav.map(([label, icon]) => <button className={page === label ? 'active' : ''} onClick={() => setPage(label)} key={label}><span className="nav-icon"><NavIcon name={icon}/></span><span className="nav-label">{label}</span></button>)}</nav>
      <div className="side-bottom">
        <button className="stop" onClick={() => api.emergencyStop()}><span className="stop-icon">■</span><span className="stop-label">紧急停止</span></button>
        <button className="theme-toggle" onClick={() => setTheme(v => v === 'dark' ? 'light' : 'dark')} aria-label={theme === 'dark' ? '切换浅色模式' : '切换深色模式'}><span className="theme-icon">{theme === 'dark' ? '☼' : '☾'}</span><span className="theme-label">{theme === 'dark' ? '浅色模式' : '深色模式'}</span></button>
        <button className="collapse-toggle" onClick={() => setSidebarCollapsed(v => !v)} aria-label={sidebarCollapsed ? '展开导航栏' : '折叠导航栏'}><span className="collapse-icon">{sidebarCollapsed ? '››' : '‹‹'}</span><span className="collapse-label">{sidebarCollapsed ? '展开' : '收起'}</span></button>
      </div>
    </aside>
    <main className="main"><header className="top"><span>个人工作台</span><span>/</span><b>{pageTitle}</b><span className="grow"/><span className="tag">Windows x64 · 本地模式</span><span className="tag">审计链 ✓</span></header>
      {page === '终端' ? <Terminal session={session} light={theme === 'light'} open={agentOpen} setOpen={setAgentOpen}/> : page === '主机' ? <HostsPage hosts={hosts} connect={connect}/> : page === 'SFTP' ? <SftpPage/> : page === '审计' ? <AuditPage/> : page === '设置' ? <SettingsPage theme={theme} setTheme={setTheme}/> : <Dashboard hosts={hosts} connect={connect}/>} 
    </main>
  </div>;
}

function Dashboard({ hosts, connect }: { hosts: Host[]; connect: (h: Host) => void }) { return <section className="content"><div className="hero"><div><h1>早上好，John</h1><p>查看连接状态、待审批操作和最近活动。</p></div><div className="actions"><button className="btn" onClick={() => hosts[0] && connect(hosts[0])}>＋ 新建主机</button><button className="btn primary" onClick={() => hosts[0] && connect(hosts[0])}>打开终端</button></div></div><div className="cards"><Metric label="活动会话" value="3 / 8" hint="↑ 2 个已就绪"/><Metric label="待审批操作" value="2" hint="最高风险：high" tone="yellow"/><Metric label="今日审计事件" value="128" hint="哈希链连续"/><Metric label="传输任务" value="1" hint="下载进行中 · 42%"/></div><div className="dashboard-grid"><div className="card"><h3>主机状态</h3>{hosts.slice(0, 3).map(h => <div className="host-row" key={h.id}><div><b>{h.name}</b>{h.is_production && <span className="badge red">生产</span>}<br/><span className="muted">{h.username}@{h.address}</span></div><span className="badge green">● ready</span></div>)}</div><div className="card"><h3>待处理审批</h3><div className="approval high"><b>生产主机 · 覆盖配置文件</b><p className="muted">nginx-prod-01 · high</p><code>cp app.conf app.conf.bak && mv /tmp/app.conf ./app.conf</code><button className="btn primary">查看并审批</button></div><div className="approval medium"><b>测试机 · 重启服务</b><p className="muted">test-api-02 · medium</p><code>systemctl restart api</code></div></div></div></section>; }
function Metric({ label, value, hint, tone }: { label: string; value: string; hint: string; tone?: string }) { return <div className="card metric-card"><span className="muted">{label}</span><div className={'metric ' + (tone ?? '')}>{value}</div><span className={'metric-hint ' + (tone ?? '')}>{hint}</span></div>; }

function HostsPage({ hosts, connect }: { hosts: Host[]; connect: (h: Host) => void }) { const [query, setQuery] = useState(''); const filtered = hosts.filter(h => `${h.name} ${h.address} ${h.username}`.toLowerCase().includes(query.toLowerCase())); return <section className="content"><div className="hero"><div><h1>主机管理</h1><p>直连 SSH 和单级堡垒机端点。</p></div><div className="actions"><button className="btn">筛选</button><button className="btn primary">＋ 新建主机</button></div></div><div className="card"><input className="search" value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索名称、地址或用户名…"/><table className="table"><thead><tr><th>主机</th><th>连接</th><th>认证</th><th>环境</th><th>状态</th><th>操作</th></tr></thead><tbody>{filtered.map(h => <tr key={h.id}><td><b>{h.name}</b><br/><span className="muted">{h.username}@{h.address}</span></td><td>{h.connection_type === 'bastion_endpoint' ? '堡垒机' : '直连 SSH'}</td><td><span className="badge blue">{h.auth_method === 'ssh_agent' ? 'SSH Agent' : h.auth_method === 'private_key' ? 'Credential Manager' : '密码'}</span></td><td><span className={'badge ' + (h.is_production ? 'red' : '')}>{h.is_production ? '生产' : '测试'}</span></td><td><span className="badge green">● ready</span></td><td><button className="btn" onClick={() => connect(h)}>打开终端</button></td></tr>)}</tbody></table></div></section>; }

function SftpPage() { const [path, setPath] = useState('~'); const files = [['📁', 'releases', '目录'], ['📄', 'app.conf', '12 KB · 09:14'], ['📦', 'release.tar.gz', '1.2 GB · 09:05'], ['📄', 'README.md', '4 KB · 08:21']]; return <section className="content"><div className="hero"><div><h1>SFTP 文件管理</h1><p>连接后默认访问远端 <code>~</code> · 单文件上限 20 GiB</p></div><div className="actions"><button className="btn" onClick={() => setPath(path === '~' ? '~/releases' : '~')}>＋ 新目录</button><button className="btn primary">↑ 上传文件</button></div></div><div className="split-grid"><div className="card"><div className="breadcrumbs">⌂ / <b>{path}</b></div>{files.map(([icon, name, meta]) => <button className="file-row" key={name} onClick={() => name === 'releases' && setPath('~/releases')}><span>{icon}</span><b>{name}</b><span className="muted">{meta}</span></button>)}</div><div className="card"><h3>传输队列</h3><div className="transfer-row"><b>release.tar.gz</b><span className="badge">下载中</span><p className="muted">prod-api-01 → 本地选择目录</p><div className="progress"><i/></div><small className="muted">512 MB / 1.2 GB <button className="btn">暂停</button></small></div><div className="transfer-row"><b>app.conf</b><span className="badge green">已完成</span><p className="muted">上传 · 原子替换 · 已写入审计</p></div></div></div></section>; }

function AuditPage() { return <section className="content"><div className="hero"><div><h1>本地审计</h1><p>SHA-256 追加哈希链 · 仅当前 Windows 用户可见</p></div><div className="actions"><button className="btn">导出 JSONL</button><button className="btn">校验链</button></div></div><div className="cards"><Metric label="链状态" value="✓ 连续" hint="追加写入正常"/><Metric label="事件总数" value="12,480" hint="当前数据库"/><Metric label="最近事件" value="09:21:44" hint="command.executed"/><Metric label="保留期限" value="90 天" hint="本地配置"/></div><div className="card table-card"><table className="table"><thead><tr><th>时间</th><th>事件</th><th>目标</th><th>操作者</th><th>风险</th><th>哈希</th></tr></thead><tbody><tr><td>09:21:44</td><td>command.executed</td><td>prod-api-01</td><td>Agent / allowlist</td><td><span className="badge green">low</span></td><td>8f2a…c19d</td></tr><tr><td>09:18:02</td><td>approval.created</td><td>prod-api-01</td><td>John</td><td><span className="badge yellow">high</span></td><td>219a…0f31</td></tr><tr><td>09:14:38</td><td>sftp.completed</td><td>prod-api-01</td><td>John</td><td><span className="badge">medium</span></td><td>61bd…e8c2</td></tr></tbody></table></div></section>; }

function SettingsPage({ theme, setTheme }: { theme: 'dark' | 'light'; setTheme: (t: 'dark' | 'light') => void }) { return <section className="content"><div className="hero"><div><h1>设置</h1><p>个人版本地配置和安全策略。</p></div><button className="btn primary">保存设置</button></div><div className="settings-grid"><div className="card"><h3>模型配置</h3><p className="setting-line">Provider <span className="badge">Ollama</span></p><p className="setting-line">模型 <b>qwen2.5-coder:14b</b></p><p className="setting-line">流式输出 <span className="badge green">已启用</span></p><p className="setting-line">配置文件 <code>%USERPROFILE%\\.termpilot\\config.toml</code></p></div><div className="card"><h3>执行策略</h3><p className="setting-line">默认模式 <span className="badge yellow">ask_before_execute</span></p><p className="setting-line">生产主机自动执行 <span className="badge red">关闭</span></p><p className="setting-line">只读白名单 <span className="badge green">3 条规则</span></p><p className="setting-line">连续自动命令上限 <b>5</b></p></div><div className="card"><h3>本地数据</h3><p className="setting-line">数据库 <span className="ok-text">可写</span></p><p className="setting-line">审计保留 <b>90 天</b></p><p className="setting-line">远程默认目录 <code>~</code></p><p className="setting-line">日志 <span className="muted">脱敏 · 滚动 10 MB</span></p></div><div className="card"><h3>外观与安全</h3><p className="setting-line">主题 <button className="btn" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? '深色模式' : '浅色模式'}</button></p><p className="muted">密码、私钥和 Token 不会写入 SQLite 或发送给模型。</p><p className="muted">本地哈希链可发现普通篡改，但不抵御本机管理员。</p></div></div></section>; }

function ShellSurface({ light }: { light: boolean }) { const host = useRef<HTMLDivElement>(null); useEffect(() => { if (!host.current) return; const term = new XTerminal({ convertEol: true, cursorBlink: true, fontFamily: 'Consolas, monospace', fontSize: 13, theme: { background: light ? '#ffffff' : '#080d18', foreground: light ? '#24344a' : '#cbd6ed', cursor: light ? '#24344a' : '#cbd6ed' } }); const fit = new FitAddon(); term.loadAddon(fit); term.open(host.current); fit.fit(); term.writeln('TermPilot SSH session · fingerprint verified'); term.writeln('\x1b[32m● Connected to prod-api-01 (10.0.10.21)\x1b[0m'); term.writeln('Last login: Fri Sep 04 09:12:03 2026 from 10.0.0.5'); term.writeln(''); term.writeln('\x1b[94mops@prod-api-01:~$\x1b[0m uname -a'); term.writeln('Linux prod-api-01 5.15.0-118-generic x86_64 GNU/Linux'); term.writeln('\x1b[94mops@prod-api-01:~$\x1b[0m df -h /var'); term.writeln('/dev/sda2 80G 52G 25G 68% /var'); term.write('\x1b[94mops@prod-api-01:~$\x1b[0m '); const resize = () => fit.fit(); window.addEventListener('resize', resize); return () => { window.removeEventListener('resize', resize); term.dispose(); }; }, [light]); return <div className="xterm-host" ref={host}/>; }

function Terminal({ light, open, setOpen }: { session?: Session; light: boolean; open: boolean; setOpen: (v: boolean) => void }) { const [agentWidth, setAgentWidth] = useState(380); const [draft, setDraft] = useState(''); const [messages, setMessages] = useState(['已连接 prod-api-01', '我会先执行安全的只读诊断。']); const shellRef = useRef<HTMLDivElement>(null); const startResize = (e: React.PointerEvent) => { e.currentTarget.setPointerCapture(e.pointerId); const move = (ev: PointerEvent) => { const rect = shellRef.current?.getBoundingClientRect(); if (!rect) return; setAgentWidth(Math.max(260, Math.min(620, rect.right - ev.clientX))); }; const stop = () => { document.removeEventListener('pointermove', move); document.removeEventListener('pointerup', stop); }; document.addEventListener('pointermove', move); document.addEventListener('pointerup', stop); }; const sendAgent = () => { const value = draft.trim(); if (!value) return; setMessages(m => [...m, value, '收到，我会先读取脱敏终端上下文。']); setDraft(''); }; return <section className="content terminal-content"><div className="hero"><div><h1>远程终端</h1><p>SSH PTY 会话 · Shell 与 Agent 分屏工作区</p></div><div className="actions"><button className="btn">＋ 连接主机</button><button className="btn red">断开当前会话</button></div></div><div ref={shellRef} className={'term-shell ' + (!open ? 'agent-hidden' : '')} style={{ gridTemplateColumns: open ? `minmax(0,1fr) ${agentWidth}px` : '1fr' }}><section className="shell-pane"><div className="term-tabs"><span className="tab active">prod-api-01 · ready ×</span><span className="tab">test-api-02 · ready ×</span><span className="tab">bastion · connecting ×</span><span className="tab-spacer"/><button className="btn plus">＋</button><button className="btn agent-toggle on" onClick={() => setOpen(!open)}>✦ Agent {open ? '已打开' : ''}</button></div><ShellSurface light={light}/><div className="shell-input"><span>ops@prod-api-01:~$</span><input placeholder="输入命令（Mock）"/></div></section>{open && <><aside className="agent-pane"><div className="agent-head"><strong>● Agent 助手</strong><span className="badge yellow">需审批</span><button className="btn" onClick={() => setOpen(false)}>×</button></div><div className="agent-body">{messages.map((m, i) => <div className={'agent-msg ' + (i % 3 === 1 ? 'user' : '')} key={`${m}-${i}`}>{m}</div>)}</div><div className="agent-compose"><input value={draft} onChange={e => setDraft(e.target.value)} onKeyDown={e => e.key === 'Enter' && sendAgent()} placeholder="询问 Agent…"/><button className="btn primary" onClick={sendAgent}>↑</button></div></aside><div className="resizer" onPointerDown={startResize}/></>}</div></section>; }
